# Generated by Django 3.2.15 on 2022-09-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=128, unique=True, verbose_name='title')),
                ('subtitle', models.CharField(default='subtitle', max_length=128, verbose_name='subtitle')),
                ('body', models.TextField()),
                ('category', models.CharField(max_length=128)),
                ('created_time', models.DateTimeField(verbose_name='created time')),
                ('modified_time', models.DateTimeField(verbose_name='modified time')),
            ],
        ),
    ]
