# Generated by Django 3.2.15 on 2023-02-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='count',
        ),
        migrations.AddField(
            model_name='category',
            name='article_number',
            field=models.IntegerField(default=0, verbose_name='article number'),
            preserve_default=False,
        ),
    ]
