# Generated by Django 3.2.15 on 2023-02-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20230212_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='post_number',
            field=models.IntegerField(default=0, verbose_name='post number'),
        ),
    ]
